apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vvn-pc-clockpresales-receive-lmb
  description: some description
  annotations:
    backstage.io/source-location: url:todo

  tags:
    - lambda
    - aws
    


spec:
  type: lambda
  system: vvnclockpresales
  lifecycle: production
  owner: team_veilen_dev
  dependsOn:
    - component:default/vvn-pc-clockpresales-consolidatebatch-lmb
    - resource:default/vvn-pc-clockpresales-consolidatebatch-queue

