apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fsobs-sud-lmb
  description: some description
  annotations:
    backstage.io/source-location: url:todo

  tags:
    - lambda
    - aws
    


spec:
  type: lambda
  system: team_international
  lifecycle: production
  owner: team_international_dev
  dependsOn:
    - resource:default/fsobs-sud-queue
    - resource:default/settlementstates-shared
    - resource:default/fesci-cds-api
    - resource:default/fso-ces-api
