apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fso-btc-lmb
  description: some description
  annotations:
    backstage.io/source-location: url:todo

  tags:
    - lambda
    - aws
    


spec:
  type: lambda
  system: team_international
  lifecycle: production
  owner: team_veilen_dev

  providesApis:
    <providesApis>