apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fsoci-cis-lmb
  description: some description
  annotations:
    backstage.io/source-location: url:todo

  tags:
    - lambda
    - aws
    


spec:
  type: lambda
  system: team_international
  lifecycle: production
  owner: team_international_dev
  dependsOn:
    - component:default/fesci-cds-lmb
    - resource:default/fsoci-cis-api
    - resource:default/consumptionitemversies-shared
    - resource:default/consumptionitemrequests-shared
    - resource:default/fesci-cds-api
