apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fso-upd-lmb
  description: some description
  annotations:
    backstage.io/source-location: url:todo

  tags:
    - lambda
    - aws
    


spec:
  type: lambda
  system: team_international
  lifecycle: production
  owner: team_international_dev
  dependsOn:
    - component:default/fesci-cds-lmb
    - resource:default/fso-upd-queue
    - resource:default/settlement-states-shared
    - resource:default/fesci-cds-api
