apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: consumptionitemversies-shared
  description: some description
spec:
  type: dynamodb
  owner: team_veilen_dev
  system: team_international