apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fesci-cds-lmb
  description: some description
  annotations:
    backstage.io/source-location: url:todo

  tags:
    - lambda
    - aws
    


spec:
  type: lambda
  system: team_international
  lifecycle: production
  owner: team_international_dev
  dependsOn:
    - component:default/fso-upd-lmb
    - component:default/fsoci-cis-lmb
    - component:default/fsobs-sud-lmb
    - component:default/fsobs-bts-lmb
    - resource:default/fesci-cds-api
    - resource:default/citrelatedentity-shared
