apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vvn-pc-clockpresales-consolidatebatch-lmb
  description: some description
  annotations:
    dev.azure.com/project-repo:  <organisation>/<project>
    sentry.io/project-slug: <organisation>-<project>
  tags:
    <tags>    
  links:
    <links>

spec:
  type: lambda
  system: vvnclockpresales
  lifecycle: production
  owner: team_veilen_dev