apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vvn-clockconsolidation-orderedbatch-lmb
  description: some description
  annotations:
    backstage.io/source-location: url:todo

  tags:
    - lambda
    - aws
    


spec:
  type: lambda
  system: vvnconsilidations
  lifecycle: production
  owner: team_veilen_dev

