apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fsoci-bts-lmb
  description: some description
  annotations:
    backstage.io/source-location: url:todo

  tags:
    - lambda
    - aws
    


spec:
  type: lambda
  system: team_international
  lifecycle: production
  owner: team_international_dev
  dependsOn:
    - component:default/fsobs-cis-lmb
    - resource:default/fsoci-bts-queue
    - resource:default/fsobs-cis-api
